### ISSUE TITLE
download and attach source jars in Eclipse

### ISSUE THREAD

**Issue by fommil** [sbt/sbt-eclipse#133]
`sbt update-classifiers` will grab the sources for the dependencies, but `sbt eclipse` doesn't do anything with them.

It is possible to manually add the sources to the jars within Eclipse, but this information gets lost every time `sbt eclipse` is ran.

Please attach sources to dependencies in the Eclipse project, so that source browsing is possible from the IDE.

**Comment by Yuhta** [comment]
What if my coworker does not install sbt-eclipse?  Would  `EclipseKeys` in `build.sbt` error out for them?  **Shouldn't this be a plugin setting instead of project setting?**
