### ISSUE TITLE
Eclipse and SBT output collide

### ISSUE THREAD

**Issue by benmccann** [sbt/sbt-eclipse#230]
sbteclipse is creating the following in my .classpath file:

```
<classpathentry kind="src" path="src/main/scala" output="target/scala-2.11/classes"/>
<classpathentry kind="src" path="src/main/java" output="target/scala-2.11/classes"/>
<classpathentry kind="src" path="src/test/scala" output="target/scala-2.11/test-classes"/>
<classpathentry kind="src" path="src/test/java" output="target/scala-2.11/test-classes"/>
```

This is really bad because it sends the Eclipse output to the same directory where SBT is compiling to. This creates situations with my program crashing unexpectedly, compiling taking forever and recompiling the same files over and over again in loops, compiling and tests failing, etc. Changing this so that they don't share output directories does mean that eclipse and SBT both compile the project doing extra work, but I've never had it work without crashing with the current setup. In the long term, creating the [SBT server](https://github.com/sbt/sbt/wiki/Client-server-split) and hooking into would be a solution for this.

I'd like the output to look like this instead:

```
<classpathentry kind="src" path="src/main/scala"/>
<classpathentry kind="src" path="src/main/java"/>
<classpathentry kind="src" path="src/test/scala"/>
<classpathentry kind="src" path="src/test/java"/>
```

I can manually edit the file after it's generated, so I've verified that this looks to work much better. Could we make this the default output? Or is there at least a setting for it?

I'm using Play, but [they don't seem to be overriding the defaults](https://github.com/playframework/playframework/blob/master/framework/src/sbt-plugin/src/main/scala/PlayEclipse.scala).

**Comment by er1c** [comment]
Hmm, this is why we just use the `EclipseKeys.eclipseOutput` setting =- to avoid SBT vs eclipse collisions (https://github.com/frugalmechanic/fm-sbt-common/blob/master/src/main/scala/fm/sbt/FMCommon.scala#L22)

**Comment by er1c** [comment]
Dumb question, any chance you can dig up the Eclipse documentation that documents the format of the  `.classpath` files?  I tried doing a cursory search and didn't come up with much.

**Comment by benmccann** [comment]
Yes, you can certainly set `EclipseKeys.eclipseOutput`, but it was silly to have the default be broken so that everyone has to set that setting.

I've never seen Eclipse documentation regarding the format of their files, but please share if you find any.

**Comment by er1c** [comment]
@benmccann I haven't tested it, is there any unit test to verify the `EclipseKeys.eclipseOutput := Some(".target"),` would continue to output the `output=".target/scala-2.11/classes"` attribute?

**Comment by benmccann** [comment]
The option still exists and you can still set it. It's just a different default value. You shouldn't notice any change whatsoever for https://github.com/frugalmechanic/fm-sbt-common/blob/master/src/main/scala/fm/sbt/FMCommon.scala#L22

**Comment by er1c** [comment]
@benmccann is that in the unit test somewhere or did I miss it?

**Comment by benmccann** [comment]
@er1c subc specifies eclipseOutput https://github.com/typesafehub/sbteclipse/blob/master/sbteclipse-plugin/src/sbt-test/sbteclipse/02-contents/build.sbt#L196
