### ISSUE TITLE
Use relative path for local libraries

### ISSUE THREAD

**Issue by channingwalton** [sbt/sbt-eclipse#34]
When the sbt option retrieveManaged is 'true', then it would be nice for the classpaths set in .classpath to be relative to the project root. This allows the .classpath to be shared by more than one user when devs check out code.

**Comment by norru** [comment]
Is this still not fixed in 4.0.0?

```EclipseKeys.relativizeLibs := true``` 

generates

```<classpathentry sourcepath="/home/norru/.ivy2/cache/org.slf4j/slf4j-api/srcs/slf4j-api-1.7.7-sources.jar" kind="lib" path="/home/norru/.ivy2/cache/org.slf4j/slf4j-api/jars/slf4j-api-1.7.7.jar"/>```

I would expect a mechanism to replace ```/home/norru``` with ```USER_HOME``` as suggested by a comment above.

**Comment by wasowski** [comment]
This seems to work with both keys set:
`retrieveManaged := true,
 EclipseKeys.relativizeLibs := true,`
