### ISSUE TITLE
Error using sbteclipse with SBT 1.4.0

### ISSUE THREAD

**Issue by slisaasquatch** [sbt/sbt-eclipse#375]
I get this error when running `sbt eclipse` with the newly released SBT 1.4.0.

```
[error] java.lang.NoSuchMethodError: sbt.internal.inc.Relations.products(Ljava/io/File;)Lscala/collection/immutable/Set;
[error]         at com.typesafe.sbteclipse.core.EclipsePlugin$.$anonfun$copyManagedClasses$2(EclipsePlugin.scala:117)
[error]         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:285)
[error]         at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[error]         at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[error]         at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[error]         at scala.collection.TraversableLike.map(TraversableLike.scala:285)
[error]         at scala.collection.TraversableLike.map$(TraversableLike.scala:278)
[error]         at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error]         at com.typesafe.sbteclipse.core.EclipsePlugin$.$anonfun$copyManagedClasses$1(EclipsePlugin.scala:116)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (Compile / compile) java.lang.NoSuchMethodError: sbt.internal.inc.Relations.products(Ljava/io/File;)Lscala/collection/immutable/Set;
```

**Comment by domizei385** [comment]
I created a fix in my fork at https://github.com/domizei385/sbteclipse.
There is one test still failing, but it is not relevant for my use case.

**Comment by bpossolo** [comment]
seeing this with sbt 1.4.7 + sbteclipse 5.2.4

**Comment by mkurz** [comment]
@domizei385 How about creating a pull request with your fixes?

**Comment by bpossolo** [comment]
@domizei385 your branch has a lot of changes that seem like they might be unnecessary to get the plugin to work.
if you don't have time to submit a PR, could you describe what the main issue is?
It looks like the issue is caused by a reference to an sbt internal method which no longer exists.
I noticed in your branch you're still using `sbt.internal.inc.Analysis`
is it safe to reference `sbt.internal.*` components or does that open it up for failure again in the future the next time the internal api changes?

**Comment by domizei385** [comment]
@bpossolo You are right. There are more changes than necessary. My initial goal was to unblock a collegue. I have not tested this on eclipse myself. Hence I lack a bit of confidence to actually turn this into a PR, but will try to look into it.
Generally this may run into issues when the internal api change, but I would worry about that once the time comes. Doing such a change exceeds my allotted time.

**Comment by domizei385** [comment]
@bpossolo You are right. There are more changes than necessary. My initial goal was to unblock a collegue. I have not tested this on eclipse myself and as I mentioned there is one test failing. Nevertheless I created the PR, but I am fairly certain that no one will care to merge it unless this test is fixed.
Generally this may run into issues when the internal api change, but I would worry about that once the time comes. Doing such a change exceeds my allotted time.

**Comment by mkurz** [comment]
@bpossolo You got a PM in https://discuss.lightbend.com/

**Comment by ProChirathF** [comment]
Any plans of a fix for this issue? We would like to use sbt 1.5.0 with PlayFramework v2.8.8

**Comment by mkurz** [comment]
A couple of weeks ago I had a look what the problem is and I think back then I found out what's going on. Maybe I find them the next days to provide a pull request with a fix (but I am busy currently)

**Comment by ProChirathF** [comment]
Thanks, looking forward to a fix.

**Comment by prosasankad** [comment]
Hi,
Any progress on this issue ? We need to upgrade to newer sbt version due to log4j vulnerability but this issue stops us from upgrading

Thanks

**Comment by mkurz** [comment]
No time to work on it yet, but it's on my radar.

**Comment by mkurz** [comment]
It took ages, but finally, after 5 years, I just released a new sbt-eclipse version: https://github.com/sbt/sbt-eclipse/releases/tag/6.0.0 with support for newer (1.4+) sbt versions.
Be aware that the groupId and artifact name changed, see the release notes.
Also, from now on, releases are hosted on Maven Central, so you don't need to configure any resolvers: https://repo1.maven.org/maven2/com/github/sbt/sbt-eclipse_2.12_1.0/6.0.0/
